src/LaunchDarkly.EventSource/EventSourceService.cs, src/LaunchDarkly.EventSource/EventSourceServiceCancelledException.cs, src/LaunchDarkly.EventSource/EventSourceServiceUnsuccessfulResponseException.cs, test/LaunchDarkly.EventSource.Tests/EventSourceTests.cs
This is necessary in order to implement the desired "stop trying to do things if we get a 401 error" logic in the client. Previously, the information we passed to EventSource error handlers only contained a string description of the error; this adds an exception subclass that contains the status code.
=> make HTTP status code available to error handlers

src/LaunchDarkly.EventSource/EventSource.cs, src/LaunchDarkly.EventSource/IEventSource.cs
This is so the event source can be mocked out in SDK tests.
=> add an interface for EventSource to facilitate testing

src/LaunchDarkly.EventSource/Configuration.cs, src/LaunchDarkly.EventSource/EventSourceService.cs, test/LaunchDarkly.EventSource.Tests/EventSourceTests.cs
We'll need to be able to send a REPORT body for mobile/Xamarin.
=> Add HTTP method/body params to EventSource config

src/LaunchDarkly.EventSource/LaunchDarkly.EventSource.csproj
It wasn't being used in this assembly.
=> remove unnecessary Newtonsoft.Json dependency from eventsource

console-app-dotnetcore/Program.cs, src/LaunchDarkly.EventSource/EventSource.cs
https://app.clubhouse.io/launchdarkly/story/21565/net-sdk-does-not-wait-before-reconnecting-to-stream
I tested this by running the test console app in this repo against a local streamer, then killing the streamer. Prior to this fix, it would log messages of "reconnecting after ____ milliseconds" but the next reconnect attempt would happen immediately.
=> when there's a backoff delay, actually do the delay

src/LaunchDarkly.EventSource/LaunchDarkly.EventSource.csproj
Already did this in the rest of the SDK, but forgot about the event source library.
=> change package references to framework references for System assemblies

src/LaunchDarkly.EventSource/ExponentialBackoffWithDecorrelation.cs
See [ch21070](https://app.clubhouse.io/launchdarkly/story/21070/net-xamarin-opening-a-brand-new-stream-causes-reconnecting-log-messages) for more details.
=> don't share the same reconnect counter across all streams

src/LaunchDarkly.EventSource/EventSource.cs, src/LaunchDarkly.EventSource/EventSourceService.cs, test/LaunchDarkly.EventSource.Tests/EventSourceTests.cs
As reported [here](https://github.com/launchdarkly/dotnet-client/issues/88), the stream would not reconnect if it received an HTTP error code from the server. This was due to accidentally reusing the same CancellationToken to mean both "give up on the current HTTP request" and "give up permanently on the whole event source".
We did in fact have some unit tests with a fake HTTP server returning various errors. But the unit tests all relied on the wrong behavior, i.e. they expected the stream to close itself permanently instead of reconnecting. So I've reworked the tests too - I'd particularly appreciate comments on whether you think the tests now have adequate coverage of the various failure modes. (I also tested this manually against a fake stream.)
=> fix stream reconnect logic

src/LaunchDarkly.EventSource/EventSourceService.cs, src/LaunchDarkly.EventSource/Util.cs, test/LaunchDarkly.EventSource.Tests/EventSourceTests.cs
https://app.clubhouse.io/launchdarkly/story/24949/net-sdk-leaks-an-unhandled-exception-in-lambda
This turned out to be easy to reproduce: I just ran our test console app with a short timeout, and set a global event handler the same way I did in the new unit test here. The event always fired after a timeout happened, although the timing was unpredictable (the test makes it predictable by forcing GC).
There may be other places where we have this problem, I'm not sure yet.
=> prevent unobserved exception when read timeout happens

src/LaunchDarkly.EventSource/EventSource.cs
The [MS documentation](https://docs.microsoft.com/en-us/dotnet/standard/threading/cancellation-in-managed-threads) says that you should always call `Dispose()` explicitly on a `CancellationTokenSource` when you're done with it. I looked into this a bit more and it seems that it's very unlikely that the way we're using this class could leak any unmanaged resources (most sources seem to agree that the potential for a leak is only if you either 1. use `CreateLinkedTokenSource` or 2. set a timeout) but we might as well be unambiguous about it.
Also, I think the fact that `EventSource` is holding onto an `IDisposable` object means that `EventSource` itself should also be `IDisposable`, so I added that.
=> always dispose of CancellationTokenSource; add Dispose() method

src/LaunchDarkly.EventSource/EventSource.cs, src/LaunchDarkly.EventSource/EventSourceService.cs
This is a step toward a larger reorganization of the EventSource code that I'm hoping will improve both readability and reliability. I noticed while trying to diagnose a connection problem that it was a bit hard to follow how errors and connection state are being managed. See comments for details.
I also added more debug-level logging; I might remove some of this later but right now it's helpful in verifying that the logic is working as intended.
=> clean up connection/client/error management, add debug logging

src/LaunchDarkly.EventSource/Configuration.cs, src/LaunchDarkly.EventSource/ConfigurationBuilder.cs, src/LaunchDarkly.EventSource/EventSource.cs, src/LaunchDarkly.EventSource/EventSourceService.cs, test/LaunchDarkly.EventSource.Tests/ConfigurationBuilderTests.cs, test/LaunchDarkly.EventSource.Tests/EventSourceTests.cs
We've been always using the `HttpClient` constructor that can take an `HttpMessageHandler` instance, and if the application didn't specify one then we create one. There's really no reason to do this unless we actually want to override the message handler, and [on some platforms](https://nicksnettravels.builttoroam.com/post-2019-04-24-xamarin-and-the-httpclient-for-ios-android-and-windows-aspx/) it prevents the OS from substituting a better implementation.
I also did some general cleanup of the configuration classes, mostly just doc comments.
=> Don't create a default HttpMessageHandler, + misc config cleanup

src/LaunchDarkly.EventSource/EventSource.cs, src/LaunchDarkly.EventSource/EventSourceService.cs, test/LaunchDarkly.EventSource.Tests/EventSourceTests.cs, test/LaunchDarkly.EventSource.Tests/Stubs/StubHandler.cs
This patch fixes a problem that arises when disconnecting and then reconnecting.
If the `last-event-id` header is not set, the server can send old events. By setting the header to the the last event id seen, we ensure we always receive up-to-date events.
=> Set LastEventId header on reconnection

.circleci/config.yml, src/LaunchDarkly.EventSource/Properties/AssemblyInfo.cs, test/LaunchDarkly.EventSource.Tests/LaunchDarkly.EventSource.Tests.csproj
- published version is signed
- however, users don't have the key to sign the project locally
- the assembly info prev only allowed testing from a signed EventSource.Tests
- now, allows building tests in debug mode w/o signing, and allows access from unsigned EventSource.Tests
- theoretically possible for outsiders to create an unrelated EventSource.Tests to get internal access to EventSource, but those variables are already accessible through reflection
=> enable users to run tests locally

.circleci/config.yml, src/LaunchDarkly.EventSource/LaunchDarkly.EventSource.csproj
This simply adds .NET Standard 2.0 as a target so that the published package will include builds for .NET Standard 1.4, .NET Standard 2.0, and .NET Framework 4.5.
This is different from https://github.com/launchdarkly/dotnet-eventsource/pull/57, which removes .NET Standard 1.4 and also bumps the Framework version to 4.5.2. That one is intended for the next major version release; this one will be merged first and is for the current major version. The goal is to ensure that application code targeted to .NET Standard 2.0 / .NET Core 2.0 (or higher) does not have to link to .NET Standard 1.x assemblies (see https://github.com/launchdarkly/dotnet-eventsource/issues/58). Other than that, there are no functional differences between the 1.4 and 2.0 targets.
=> add .NET Standard 2.0 target

.circleci/config.yml, README.md, src/LaunchDarkly.EventSource/LaunchDarkly.EventSource.csproj, test/LaunchDarkly.EventSource.Tests/LaunchDarkly.EventSource.Tests.csproj
This removes support for .NET Framework 4.5 and 4.5.1, which have been EOL since 2016, and .NET Standard 1.x, which was only in versions of .NET Core that are now EOL.
Note that we don't currently have a CI build that runs in Windows. We should add one, but there's something about the current test code that doesn't work right in Windows which I'm still trying to figure out.
=> bump targeted platform versions to .NET Framework 4.5.2, .NET Standard 2.0

src/LaunchDarkly.EventSource/Configuration.cs, src/LaunchDarkly.EventSource/ConfigurationBuilder.cs, src/LaunchDarkly.EventSource/EventSource.cs, src/LaunchDarkly.EventSource/EventSourceService.cs, src/LaunchDarkly.EventSource/LaunchDarkly.EventSource.csproj, test/LaunchDarkly.EventSource.Tests/ConfigurationBuilderTests.cs, test/LaunchDarkly.EventSource.Tests/EventSourceLoggingTests.cs
This migrates EventSource to the LaunchDarkly.Logging abstraction that we're planning to use for our .NET-based libraries in the future, removing the dependency on Common.Logging (we will be releasing an adapter so that LaunchDarkly.Logging can be bridged to Common.Logging very simply). This is using an alpha version as the library isn't in GA yet.
This PR doesn't change EventSource's current logging behavior in any other way. We'll probably want to add more detail to the log output and revise some of its phrasing, but this PR is just about the API it uses.
=> (4.0) use LaunchDarkly.Logging

src/LaunchDarkly.EventSource/Configuration.cs, src/LaunchDarkly.EventSource/ConfigurationBuilder.cs, src/LaunchDarkly.EventSource/EventSource.cs, src/LaunchDarkly.EventSource/Resources.Designer.cs, src/LaunchDarkly.EventSource/Resources.resx, test/LaunchDarkly.EventSource.Tests/ConfigurationBuilderTests.cs, test/LaunchDarkly.EventSource.Tests/ConfigurationTests.cs, test/LaunchDarkly.EventSource.Tests/EventSourceTests.cs
This enables the usage of an existing httpClient. This can be useful if you can not provide an apropriate MessageHandler. In my specific case I have to reuse an exiting httpClient with some included security handlers. This existing httpClient is provided by a (external) factory so i can not provide the handlers to the eventsource myself.
=> Usage of custom httpClient

.circleci/config.yml, test/LaunchDarkly.EventSource.Tests/EventSourceEndToEndTest.cs, test/LaunchDarkly.EventSource.Tests/EventSourceReconnectingTest.cs, test/LaunchDarkly.EventSource.Tests/LaunchDarkly.EventSource.Tests.csproj, test/LaunchDarkly.EventSource.Tests/Stubs/StubHandler.cs
There were two reasons why we didn't have CI tests for this library running in Windows till now:
1. Originally, CircleCI didn't support it.
2. Then, we tried and found out that the WireMock.Net library we were using for an embedded HTTP server had some compatibility problems in .NET Framework.
Those are no longer relevant, but I found a few more test issues - see PR comments.
=> make CI tests work in Windows

src/LaunchDarkly.EventSource/EventSource.cs, src/LaunchDarkly.EventSource/EventSourceService.cs, src/LaunchDarkly.EventSource/EventSourceServiceUnsuccessfulResponseException.cs, src/LaunchDarkly.EventSource/ReadTimeoutException.cs, src/LaunchDarkly.EventSource/Resources.Designer.cs, src/LaunchDarkly.EventSource/Resources.resx, test/LaunchDarkly.EventSource.Tests/AsyncHelpersTest.cs, test/LaunchDarkly.EventSource.Tests/EventSourceHttpBehaviorTest.cs
This library's error messages, which date back to a pretty old first version from before we had any style conventions at all, have some idiosyncratic choices:
* Referring to the server endpoint as the "EventSource API" (`A timeout occurred while reading the request from the remote EventSource API`)— that's incorrect, the EventSource API would either be this library's own EventSource class or the _browser JavaScript API_ of the same name; the protocol used by the server is called Server-Sent Events.
* Random capitalization (`Remote EventSource API returned Http Status Code 204.`), (`Http Response contained no content.`)
* Sometimes ending with a period, sometimes not
* The programmatic names for the messages(*) are using underscore delimiters, inconsistent with .NET symbol naming …
=> clean up error messages

src/LaunchDarkly.EventSource/Configuration.cs, src/LaunchDarkly.EventSource/ConfigurationBuilder.cs, src/LaunchDarkly.EventSource/EventSource.cs, test/LaunchDarkly.EventSource.Tests/ConfigurationBuilderTest.cs
One aspect of .NET's HTTP implementation that's different from many other platforms is that it doesn't really have a notion of a distinct TCP connection timeout, or a read (socket) timeout. Those things do exist in its lower-level TCP implementation, but they're not surfaced in HttpClient. We rolled our own implementation of the read timeout for EventSource, but we misleadingly provided a `ConnectionTimeout` property that was being used to set the property `HttpClient.Timeout`... which is not the connection timeout at all, it's "time till we start receiving a response".
_Some_ .NET platforms (.NET Core 2.1+ and .NET 5+) do now have a connection timeout, but not as a property of the client— it's a property of the class `SocketsHttpHandler`. Since EventSource already gives you the ability …
=> rename ConnectionTimeout to ResponseStartTimeout

.ldrelease/build-docs.ps1, .ldrelease/config.yml, .ldrelease/zip-helper.ps1
This is a change to our release procedures that I'd like to integrate into our regular release tool for all of our .NET projects, and it'd be nice to use it for the upcoming LD .NET SDK 6.0 release, but it's easiest to test it on a single relatively independent project first.
We've been using Microsoft's obsolete Sandcastle Help File Builder tool to generate HTML documentation from doc comments. Besides being very old and unmaintained, it can only run in Windows, but for many years there was no real alternative (Doxygen is supposed to be compatible with C#, but I could never get it to work). However, in the last few years Microsoft has been improving its newer DocFX tool to the point where it seems usable for our purposes. DocFX has some idiosyncracies but it's maintained, and since it's …
=> use DocFX to generate HTML docs

src/LaunchDarkly.EventSource/ConfigurationBuilder.cs, test/LaunchDarkly.EventSource.Tests/ConfigurationBuilderTest.cs, test/LaunchDarkly.EventSource.Tests/EventSourceHttpBehaviorTest.cs, test/LaunchDarkly.EventSource.Tests/LaunchDarkly.EventSource.Tests.csproj
Just a few bits I wanted to round out before merging this externally contributed feature (see: https://github.com/launchdarkly/dotnet-eventsource/pull/85).
=> tests/comment edits for new HttpRequestModifier feature

src/LaunchDarkly.EventSource/LaunchDarkly.EventSource.csproj
I had meant to do this as part of the platform compatibility updates. There are no API differences in LaunchDarkly.Logging between 1.x and 2.x, it was just a change in target frameworks, so either is acceptable. This can be a patch release of EventSource.
=> allow using LaunchDarkly.Logging 2.x
